services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - '3000:3000'
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_backend
  #   ports:
  #     - '8090:8080'
